#!/usr/bin/env bash

selected=$(find $HOME/programming/ -mindepth 1 -maxdepth 2 -type d | fzf)

if [[ -z $selected ]]; then
  exit 0
fi


prefix="$HOME/programming/"
echo "Selected: $selected"
prefixelim=${selected#"$prefix"}

echo "Prefixelim: $prefixelim"
session_type=${prefixelim%/*}
echo "Session type: $session_type"

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmuxinator start $session_type-dev "$selected" $selected_name
  exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
  tmuxinator start $session_type-dev "$selected" $selected_name
  exit 0
fi

exit 0
