#!/usr/bin/env bash

tmux_running=$(pgrep tmux)
if [[ -z $tmux_running ]]; then
  exit 1
fi
selected=$(tmux list-sessions | fzf)

if [[ -z $selected ]]; then
  exit 0
fi

selected_fmt=${selected%%:*}
echo "Session: $selected_fmt"


if [[ -n $TMUX ]]; then
  echo "tmux switch-client -t $selected_fmt"
  tmux switch-client -t $selected_fmt
  exit 0
else
  echo "Tmux not running $TMUX"
  exit 1
fi

if ! tmux has-session -t=$selected_fmt 2> /dev/null; then
  echo "Session $selected_fmt not found"
  exit 1
fi

exit 1
